import {
  Building2,
  Calculator,
  ClipboardList,
  Hourglass,
  Landmark,
  Recycle,
  ScrollText,
  Settings,
  TriangleAlert,
  CircleCheck,
  CircleDot,
  Clock3,
  CreditCard,
  Gauge,
  Wrench,
  FileText,
  Headset,
  LayoutDashboard,
  MessagesSquare,
  ReceiptText,
  Ticket as TicketIcon,
  Building,
  Inbox,
  LocateFixed,
  Map,
  MapPinned,
  Route,
  ShieldCheck,
  Truck,
  UserRound,
  Users,
  UsersRound,
  Wallet,
  type LucideIcon,
} from "lucide-react";
import type { Role, TicketStatus } from "@/lib/types";

/*
 * The app's icon vocabulary in one place, so a concept always wears the same
 * glyph. Kept apart from lib/navigation because Edge middleware imports that
 * module and has no use for React components.
 */

export const NAV_ICONS: Record<string, LucideIcon> = {
  "/client": Wallet,
  "/client/statement": FileText,
  "/client/track": MapPinned,
  "/client/pickups": ClipboardList,
  "/client/report": TriangleAlert,
  "/client/support": Headset,
  "/company": LayoutDashboard,
  "/company/clients": Users,
  "/company/map": Map,
  "/company/fleet": Gauge,
  "group:fleet": Truck,
  "group:finance": Landmark,
  "group:team": UsersRound,
  "group:care": Headset,
  "/company/tickets": TicketIcon,
  "/company/invoices": ReceiptText,
  "/company/desk": Inbox,
  "/company/staff": Users,
  "/company/departments": Building,
  "/company/payments": CreditCard,
  "/company/arrears": Hourglass,
  "/company/statements": FileText,
  "/company/finance": Calculator,
  "/company/pickups": ClipboardList,
  "/company/dumping": TriangleAlert,
  "/company/impact": Recycle,
  "/company/support": MessagesSquare,
  "/company/settings": Settings,
  "/company/audit": ScrollText,
  "/collector": Route,
  "/collector/vehicle": Wrench,
  "/collector/map": LocateFixed,
  "/admin": LayoutDashboard,
  "/admin/clients": UsersRound,
  "/admin/map": Map,
  "/admin/companies": Building2,
  "/admin/dumping": TriangleAlert,
  "/admin/access": ShieldCheck,
  "/admin/users": Users,
  "/admin/settings": Settings,
  "/admin/audit": ScrollText,
};

export const ROLE_ICONS: Record<Role, LucideIcon> = {
  client: UserRound,
  company: Building2,
  collector: Truck,
  admin: ShieldCheck,
};

export const TICKET_ICONS: Record<TicketStatus, LucideIcon> = {
  Open: CircleDot,
  Pending: Clock3,
  Resolved: CircleCheck,
};
